# Generated by Django 2.1.4 on 2021-08-14 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0002_delete_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email')),
                ('admin', models.BooleanField(default=False)),
                ('estado', models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='I', max_length=1)),
                ('firebase_uid', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
