# Generated by Django 2.1.4 on 2021-08-26 02:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20210821_0037'),
    ]

    operations = [
        migrations.AddField(
            model_name='rol',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='api.Usuario'),
        ),
    ]
