# Generated by Django 2.1.4 on 2021-08-26 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_usuario_rol'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rol',
            name='usuario',
        ),
    ]
