# Generated by Django 2.1.4 on 2021-08-31 03:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_proyecto'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='scrum_master',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proyecto_scrum_master', to='api.Usuario'),
        ),
    ]
