# Generated by Django 2.1.4 on 2021-09-09 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_proyecto_scrum_master'),
    ]

    operations = [
        migrations.CreateModel(
            name='PermisoProyecto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='', max_length=255)),
                ('codigo', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PlantillaRolProyecto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='', max_length=255)),
                ('permisos', models.ManyToManyField(to='api.PermisoProyecto')),
            ],
        ),
    ]
