# Generated by Django 2.1.4 on 2021-09-20 02:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_horario'),
    ]

    operations = [
        migrations.AddField(
            model_name='miembro',
            name='horario',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='miembro', to='api.Horario'),
        ),
    ]
