# Generated by Django 2.1.4 on 2021-09-20 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_auto_20210920_0652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horario',
            name='miembro',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='horario', to='api.Miembro'),
        ),
    ]
