# Generated by Django 2.1.4 on 2021-09-23 03:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_auto_20210920_0720'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserStory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('horas_estimadas', models.IntegerField()),
                ('prioridad', models.IntegerField()),
                ('estado', models.CharField(choices=[('P', 'Pendiente'), ('R', 'Release'), ('C', 'Cancelado')], default='P', max_length=1)),
                ('fecha_release', models.DateField()),
                ('fecha_creacion', models.DateField()),
                ('estado_estimacion', models.CharField(max_length=1)),
                ('product_backlog', models.BooleanField()),
                ('desarrollador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Miembro')),
            ],
        ),
    ]
