# Generated by Django 2.1.4 on 2021-09-24 01:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_userstory'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductBacklog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proyecto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='product_backlogs', to='api.Proyecto')),
            ],
        ),
        migrations.CreateModel(
            name='RegistroUserStory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_antes', models.CharField(max_length=255)),
                ('descripcion_antes', models.TextField()),
                ('hora_estimada_antes', models.IntegerField()),
                ('prioridad_antes', models.IntegerField()),
                ('estado_antes', models.CharField(choices=[('P', 'Pendiente'), ('R', 'Release'), ('C', 'Cancelado')], max_length=1)),
                ('nombre_despues', models.CharField(max_length=255)),
                ('descripcion_despues', models.TextField()),
                ('hora_estimada_despues', models.IntegerField()),
                ('prioridad_despues', models.IntegerField()),
                ('estado_despues', models.CharField(choices=[('P', 'Pendiente'), ('R', 'Release'), ('C', 'Cancelado')], max_length=1)),
                ('accion', models.CharField(max_length=50)),
                ('fecha', models.DateField()),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registro_user_stories', to='api.Miembro')),
                ('desarrollador_antes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registro_user_stories_antes', to='api.Miembro')),
                ('desarrollador_despues', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registro_user_stories_despues', to='api.Miembro')),
            ],
        ),
        migrations.AlterField(
            model_name='userstory',
            name='desarrollador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_stories', to='api.Miembro'),
        ),
        migrations.AlterField(
            model_name='userstory',
            name='estado_estimacion',
            field=models.CharField(choices=[('N', 'No estimado'), ('P', 'Parcial'), ('C', 'Completo')], max_length=1),
        ),
        migrations.AddField(
            model_name='registrouserstory',
            name='user_story',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='registro_user_stories', to='api.UserStory'),
        ),
        migrations.AddField(
            model_name='productbacklog',
            name='user_story',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_backlogs', to='api.UserStory'),
        ),
    ]
