# Generated by Django 2.1.4 on 2021-09-24 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_auto_20210924_0149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstory',
            name='fecha_release',
            field=models.DateField(null=True),
        ),
    ]
