# Generated by Django 2.1.4 on 2021-09-24 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_auto_20210924_0226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstory',
            name='product_backlog',
            field=models.BooleanField(default=False),
        ),
    ]
