# Generated by Django 2.1.4 on 2021-09-24 02:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_auto_20210924_0228'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registrouserstory',
            old_name='hora_estimada_antes',
            new_name='horas_estimadas_despues',
        ),
        migrations.RemoveField(
            model_name='registrouserstory',
            name='hora_estimada_despues',
        ),
        migrations.AddField(
            model_name='registrouserstory',
            name='horas_estimadas_antes',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='registrouserstory',
            name='desarrollador_antes',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='registro_user_stories_antes', to='api.Miembro'),
        ),
        migrations.AlterField(
            model_name='registrouserstory',
            name='descripcion_antes',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='registrouserstory',
            name='estado_antes',
            field=models.CharField(choices=[('P', 'Pendiente'), ('R', 'Release'), ('C', 'Cancelado')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='registrouserstory',
            name='nombre_antes',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='registrouserstory',
            name='prioridad_antes',
            field=models.IntegerField(null=True),
        ),
    ]
