# Generated by Django 2.1.4 on 2021-09-24 02:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_auto_20210924_0237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrouserstory',
            name='desarrollador_despues',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='registro_user_stories_despues', to='api.Miembro'),
        ),
    ]
