# Generated by Django 2.1.4 on 2021-09-24 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_auto_20210924_0649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrouserstory',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros', to='api.Miembro'),
        ),
        migrations.AlterField(
            model_name='registrouserstory',
            name='desarrollador_antes',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='registros_antes', to='api.Miembro'),
        ),
        migrations.AlterField(
            model_name='registrouserstory',
            name='desarrollador_despues',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='registros_despues', to='api.Miembro'),
        ),
        migrations.AlterField(
            model_name='registrouserstory',
            name='user_story',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='registro', to='api.UserStory'),
        ),
    ]
