# Generated by Django 2.1.4 on 2021-09-24 06:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_auto_20210924_0652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productbacklog',
            name='proyecto',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='product_backlog', to='api.Proyecto'),
        ),
    ]
