# Generated by Django 2.1.4 on 2021-09-27 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_auto_20210926_0139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrouserstory',
            name='descripcion_despues',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='registrouserstory',
            name='estado_despues',
            field=models.CharField(choices=[('P', 'Pendiente'), ('R', 'Release'), ('C', 'Cancelado')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='registrouserstory',
            name='horas_estimadas_despues',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='registrouserstory',
            name='nombre_despues',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='registrouserstory',
            name='prioridad_despues',
            field=models.IntegerField(null=True),
        ),
    ]
