# Generated by Django 2.1.4 on 2021-10-01 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_auto_20210927_0421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrouserstory',
            name='estado_antes',
            field=models.CharField(choices=[('P', 'Pendiente'), ('R', 'Release'), ('C', 'Cancelado'), ('E', 'Eliminado')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='registrouserstory',
            name='estado_despues',
            field=models.CharField(choices=[('P', 'Pendiente'), ('R', 'Release'), ('C', 'Cancelado'), ('E', 'Eliminado')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='userstory',
            name='descripcion',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='userstory',
            name='estado',
            field=models.CharField(choices=[('P', 'Pendiente'), ('R', 'Release'), ('C', 'Cancelado'), ('E', 'Eliminado')], default='P', max_length=1),
        ),
        migrations.AlterField(
            model_name='userstory',
            name='estado_estimacion',
            field=models.CharField(choices=[('N', 'No estimado'), ('P', 'Parcial'), ('C', 'Completo')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='userstory',
            name='horas_estimadas',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='userstory',
            name='prioridad',
            field=models.IntegerField(default=0),
        ),
    ]
