# Generated by Django 2.1.4 on 2021-10-09 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_auto_20211001_0522'),
        ('api', '0021_auto_20210922_2339'),
    ]

    operations = [
    ]
