# Generated by Django 2.1.4 on 2021-10-02 01:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_auto_20211001_0522'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sprint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('estado', models.CharField(choices=[('P', 'Pendiente'), ('A', 'Activo'), ('F', 'Finalizado')], default='P', max_length=1)),
                ('capacidad', models.IntegerField(default=0)),
                ('estado_sprint_planning', models.CharField(choices=[('N', 'No estimado'), ('P', 'Parcial'), ('C', 'Completo')], max_length=1, null=True)),
                ('planificador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sprints', to='api.Miembro')),
            ],
        ),
    ]
