# Generated by Django 2.1.4 on 2021-10-02 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_sprint'),
    ]

    operations = [
        migrations.CreateModel(
            name='SprintBacklog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sprint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sprint_backlogs', to='api.Sprint')),
                ('user_story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sprint_backlogs', to='api.UserStory')),
            ],
        ),
    ]
