# Generated by Django 2.1.4 on 2021-10-11 05:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_merge_20211009_0051'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstory',
            name='proyecto',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='user_stories', to='api.Proyecto'),
            preserve_default=False,
        ),
    ]
