# Generated by Django 2.1.4 on 2021-10-08 01:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_miembrosprint'),
    ]

    operations = [
        migrations.AddField(
            model_name='sprint',
            name='proyecto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sprints', to='api.Proyecto'),
        ),
        migrations.AlterField(
            model_name='sprint',
            name='estado_sprint_planning',
            field=models.CharField(choices=[('I', 'Iniciado'), ('F', 'Finalizado')], max_length=1, null=True),
        ),
    ]
