# Generated by Django 2.1.4 on 2021-10-08 01:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_auto_20211008_0109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sprint',
            name='estado_sprint_planning',
            field=models.CharField(choices=[('I', 'Iniciado'), ('F', 'Finalizado'), ('P', 'Pendiente')], default='P', max_length=1),
        ),
        migrations.AlterField(
            model_name='sprint',
            name='planificador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sprints', to='api.Miembro'),
        ),
    ]
