# Generated by Django 2.1.4 on 2021-10-09 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_merge_20211009_0051'),
        ('api', '0039_auto_20211008_0140'),
    ]

    operations = [
    ]
