# Generated by Django 2.1.4 on 2021-10-09 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_merge_20211009_0103'),
        ('api', '0040_merge_20211009_0239'),
    ]

    operations = [
    ]
