# Generated by Django 2.1.4 on 2021-10-11 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_userstory_proyecto'),
        ('api', '0041_merge_20211009_0251'),
    ]

    operations = [
    ]
