# Generated by Django 2.1.4 on 2021-10-11 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0043_remove_sprint_capacidad'),
        ('api', '0042_merge_20211011_1016'),
    ]

    operations = [
    ]
