# Generated by Django 2.1.4 on 2021-10-15 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0044_merge_20211011_1442'),
        ('api', '0043_merge_20211015_0045'),
    ]

    operations = [
    ]
