# Generated by Django 2.1.4 on 2021-10-19 22:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0044_merge_20211011_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='sprintbacklog',
            name='estado_kanban',
            field=models.CharField(choices=[('T', 'Todo'), ('D', 'Doing'), ('N', 'Done')], default='T', max_length=1),
        ),
        migrations.AlterField(
            model_name='userstory',
            name='desarrollador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_stories', to='api.MiembroSprint'),
        ),
        migrations.AlterField(
            model_name='userstory',
            name='estado_estimacion',
            field=models.CharField(choices=[('N', 'No estimado'), ('p', 'Parcial'), ('C', 'Completo'), ('P', 'Pendiente')], default='P', max_length=1),
        ),
        migrations.AlterField(
            model_name='userstory',
            name='horas_estimadas',
            field=models.IntegerField(default=0),
        ),
    ]
