# Generated by Django 2.1.4 on 2021-10-26 03:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0046_auto_20211015_0210'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userstory',
            name='desarrollador',
        ),
        migrations.RemoveField(
            model_name='userstory',
            name='estado_estimacion',
        ),
        migrations.RemoveField(
            model_name='userstory',
            name='horas_estimadas',
        ),
        migrations.AddField(
            model_name='sprintbacklog',
            name='desarrollador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sprint_backlogs', to='api.MiembroSprint'),
        ),
        migrations.AddField(
            model_name='sprintbacklog',
            name='estado_estimacion',
            field=models.CharField(choices=[('N', 'No estimado'), ('p', 'Parcial'), ('C', 'Completo'), ('P', 'Pendiente')], default='P', max_length=1),
        ),
        migrations.AddField(
            model_name='sprintbacklog',
            name='horas_estimadas',
            field=models.IntegerField(default=0),
        ),
    ]
