# Generated by Django 2.1.4 on 2021-10-29 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0046_auto_20211015_0210'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(default='')),
                ('horas', models.IntegerField(default=0)),
                ('fecha_creacion', models.DateField()),
                ('user_story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.UserStory')),
            ],
        ),
    ]
