# Generated by Django 2.1.4 on 2021-10-29 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0047_actividad'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividad',
            name='desarrollador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Usuario'),
        ),
    ]
