# Generated by Django 2.1.4 on 2021-10-27 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0047_auto_20211026_0303'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrouserstory',
            name='desarrollador_antes',
        ),
        migrations.RemoveField(
            model_name='registrouserstory',
            name='desarrollador_despues',
        ),
        migrations.RemoveField(
            model_name='registrouserstory',
            name='horas_estimadas_antes',
        ),
        migrations.RemoveField(
            model_name='registrouserstory',
            name='horas_estimadas_despues',
        ),
    ]
