# Generated by Django 2.1.4 on 2021-10-28 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0048_auto_20211027_1758'),
    ]

    operations = [
        migrations.AddField(
            model_name='sprintbacklog',
            name='estado_kanban',
            field=models.CharField(choices=[('T', 'Todo'), ('D', 'Doing'), ('N', 'Done')], default='T', max_length=1),
        ),
    ]
