# Generated by Django 2.1.4 on 2021-10-29 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0048_actividad_desarrollador'),
        ('api', '0048_auto_20211027_1758'),
    ]

    operations = [
    ]
