# Generated by Django 2.1.4 on 2021-10-29 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0049_sprintbacklog_estado_kanban'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observacion', models.TextField()),
                ('fecha_creacion', models.DateField()),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='api.Usuario')),
                ('user_story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='api.UserStory')),
            ],
        ),
    ]
