# Generated by Django 2.1.4 on 2021-10-29 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0049_merge_20211029_0851'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actividad',
            name='user_story',
        ),
        migrations.AddField(
            model_name='actividad',
            name='sprint_backlog',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actividades', to='api.SprintBacklog'),
        ),
    ]
