# Generated by Django 2.1.4 on 2021-11-07 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0050_auto_20211029_0950'),
        ('api', '0049_sprintbacklog_estado_kanban'),
    ]

    operations = [
    ]
