# Generated by Django 2.1.4 on 2021-11-15 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0051_merge_20211107_1257'),
        ('api', '0050_review'),
    ]

    operations = [
    ]
