# Generated by Django 2.1.4 on 2021-11-15 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0052_merge_20211115_1435'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividad',
            name='titulo',
            field=models.TextField(default=''),
        ),
    ]
