# Generated by Django 2.1.4 on 2021-11-18 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0053_actividad_titulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='sprint',
            name='fecha_fin_real',
            field=models.DateField(null=True),
        ),
    ]
