from .UserSerializer import UserSerializer
from .UsuarioSerializer import UsuarioSerializer
from .PermisoSerializer import PermisoSerializer
from .RolSerializer import RolSerializer
from .ProyectoSerializer import ProyectoSerializer
from .PermisoProyectoSerializer import PermisoProyectoSerializer
from .PlantillaRolProyectoSerializer import PlantillaRolProyectoSerializer
from .RolProyectoSerializer import RolProyectoSerializer
